const { sequelize } = require('../config/database');

// Import model definitions
const User = require('./User')(sequelize);
const Department = require('./Department')(sequelize);
const Doctor = require('./Doctor')(sequelize);
const Patient = require('./Patient')(sequelize);
const Appointment = require('./Appointment')(sequelize);
const MedicalRecord = require('./MedicalRecord')(sequelize);
const Prescription = require('./Prescription')(sequelize);
const Bill = require('./Bill')(sequelize);
const Payment = require('./Payment')(sequelize);
const AuditLog = require('./AuditLog')(sequelize);
const Report = require('./Report')(sequelize);

// ========================
// Associations
// ========================

// User <-> Doctor (1:1)
User.hasOne(Doctor, { foreignKey: 'userId', as: 'doctorProfile' });
Doctor.belongsTo(User, { foreignKey: 'userId', as: 'user' });

// User <-> Patient (1:1)
User.hasOne(Patient, { foreignKey: 'userId', as: 'patientProfile' });
Patient.belongsTo(User, { foreignKey: 'userId', as: 'user' });

// Department <-> Doctor (1:M)
Department.hasMany(Doctor, { foreignKey: 'departmentId', as: 'doctors' });
Doctor.belongsTo(Department, { foreignKey: 'departmentId', as: 'department' });

// Department head doctor
Department.belongsTo(Doctor, { foreignKey: 'headDoctorId', as: 'headDoctor', constraints: false });

// Patient <-> Appointment (1:M)
Patient.hasMany(Appointment, { foreignKey: 'patientId', as: 'appointments' });
Appointment.belongsTo(Patient, { foreignKey: 'patientId', as: 'patient' });

// Doctor <-> Appointment (1:M)
Doctor.hasMany(Appointment, { foreignKey: 'doctorId', as: 'appointments' });
Appointment.belongsTo(Doctor, { foreignKey: 'doctorId', as: 'doctor' });

// Patient <-> MedicalRecord (1:M)
Patient.hasMany(MedicalRecord, { foreignKey: 'patientId', as: 'medicalRecords' });
MedicalRecord.belongsTo(Patient, { foreignKey: 'patientId', as: 'patient' });

// Doctor <-> MedicalRecord (1:M)
Doctor.hasMany(MedicalRecord, { foreignKey: 'doctorId', as: 'medicalRecords' });
MedicalRecord.belongsTo(Doctor, { foreignKey: 'doctorId', as: 'doctor' });

// Appointment <-> MedicalRecord (1:1)
Appointment.hasOne(MedicalRecord, { foreignKey: 'appointmentId', as: 'medicalRecord' });
MedicalRecord.belongsTo(Appointment, { foreignKey: 'appointmentId', as: 'appointment' });

// MedicalRecord <-> Prescription (1:M)
MedicalRecord.hasMany(Prescription, { foreignKey: 'medicalRecordId', as: 'prescriptions' });
Prescription.belongsTo(MedicalRecord, { foreignKey: 'medicalRecordId', as: 'medicalRecord' });

// Patient <-> Bill (1:M)
Patient.hasMany(Bill, { foreignKey: 'patientId', as: 'bills' });
Bill.belongsTo(Patient, { foreignKey: 'patientId', as: 'patient' });

// Appointment <-> Bill (1:1)
Appointment.hasOne(Bill, { foreignKey: 'appointmentId', as: 'bill' });
Bill.belongsTo(Appointment, { foreignKey: 'appointmentId', as: 'appointment' });

// Bill <-> Payment (1:M)
Bill.hasMany(Payment, { foreignKey: 'billId', as: 'payments' });
Payment.belongsTo(Bill, { foreignKey: 'billId', as: 'bill' });

// Patient <-> Report (1:M)
Patient.hasMany(Report, { foreignKey: 'patientId', as: 'reports' });
Report.belongsTo(Patient, { foreignKey: 'patientId', as: 'patient' });

// MedicalRecord <-> Report
MedicalRecord.hasMany(Report, { foreignKey: 'medicalRecordId', as: 'reports' });
Report.belongsTo(MedicalRecord, { foreignKey: 'medicalRecordId', as: 'medicalRecord' });

// User <-> AuditLog (1:M)
User.hasMany(AuditLog, { foreignKey: 'userId', as: 'auditLogs' });
AuditLog.belongsTo(User, { foreignKey: 'userId', as: 'user' });

// Report generated by User
Report.belongsTo(User, { foreignKey: 'generatedBy', as: 'generator' });

module.exports = {
  sequelize,
  User,
  Department,
  Doctor,
  Patient,
  Appointment,
  MedicalRecord,
  Prescription,
  Bill,
  Payment,
  AuditLog,
  Report,
};
